### ISSUE TITLE
[FEATURE] black / isort / pytest-cov / pytest 적용

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/template#11]
## 🚀 Feature

- black / isort / pycode-cov / pylint / pytest 적용

## Motivation

- 정적 검사, 코드 커버러지, 패키지 재정렬 등 코드 가독성을 위한 패키지 추가

## Pitch

- 현재는 아무것도 안붙어있음

## Alternatives

- GitHub Action을 통해 자동으로 코드 가독성 증가

- [x] black
- [x] isort
- [x] pytest-cov
- [x] pytest
- [x] 통합

**Comment by aisolab** [comment]
codecove 관련하여 참고할만한 링크 달아 놓습니다.
- https://cjh5414.github.io/codecov-python/
- https://github.com/codecov/example-python

**Comment by dreamgonfly** [comment]
- black을 쓴다면 pylint는 쓰지 않아도 될 것 같습니다.

**Comment by dreamgonfly** [comment]
참고: black action
- https://github.com/lgeiger/black-action

**Comment by dreamgonfly** [comment]
- https://medium.com/@wkrzywiec/how-to-write-good-quality-python-code-with-github-actions-2f635a2ab09a

**Comment by aisolab** [comment]
> * black을 쓴다면 pylint는 쓰지 않아도 되지 않을까요?

저도 그렇게 생각하고 있습니다. 내가 어떤 코드를 올리던 github action에서 black이 돌아서 제 코드를 교정하고 그 코드를 레포에 올릴거라 생각하기 때문에, 다만 그 과정이  저희가 생각하는 만큼 매끄럽게 이뤄지는 지는 아직 모르겠어서 이번 주에 한번 테스트 해보려고합니다.

**Comment by dreamgonfly** [comment]
보통의 workflow는 black을 돌리고 만약 코드가 black style에 맞지 않으면 fail을 내는 것인 듯합니다. 유저가 수정 후 다시 커밋할 것을 유도하는 것이죠.

**Comment by ssaru** [comment]
오오...퇴근해서 집가면 한번 확인해보도록 하겠습니다.

**Comment by aisolab** [comment]
> 보통의 workflow는 black을 돌리고 만약 코드가 black style에 맞지 않으면 fail을 내는 것인 듯합니다. 유저가 수정 후 다시 커밋할 것을 유도하는 것이죠.

오 그렇게 생각하면 되는 군요. 좋습니다.

**Comment by ssaru** [comment]
isort GitHub Action 적용했습니다.
아래 링크 참고 부탁드립니다.

https://github.com/olance/isort-action

**Comment by ssaru** [comment]
용래님, black GitHub Action 시, black이 적용된 코드를 PR에 Commit & Push 하는 Action을 만들었는데, 이를 사용하면 어떨까 싶습니다.

작동 여부를 테스트했습니다.

@dreamgonfly @aisolab

**Comment by ssaru** [comment]
[pytest-cov](https://github.com/pytest-dev/pytest-cov)를 사용할 때, cover가 어려운 영역은 어떻게 다루는게 좋을까요?
예를들어 model이 구성된 nn의 경우는 테스트하기 곤란한 측면이 있는 것 같습니다.

어떤 기준으로 테스트하고 테스트가 성공했다고 판단할 수 있는가?

**Comment by ssaru** [comment]
pytest-cov와 pytest GitHub Action은 이렇게 적용하면 되겠네요

**pytest**
https://github.com/marketplace/actions/python-pytest-github-action
https://github.com/fylein/python-pytest-github-action
https://jangseongwoo.github.io/test/pytest_basic/

**pytest-cov**
https://github.com/pytest-dev/pytest-cov
https://github.com/codecov/codecov-action

pytest와 pytest-cov를 PR에 커멘트 달 때는 아래 Action을 활용해보면 좋을 것 같습니다.
https://github.com/marketplace/actions/pr-comment-from-file

**Comment by ssaru** [comment]
Pytest, Pytest-cov까지 붙였습니다.
PR 검토 완료되면, 통합 Action으로 묶겠습니다.

@aisolab @dreamgonfly

**Comment by aisolab** [comment]
### codecov의 codecoverage 결과를 README.md에 badge로 달기
https://stackoverflow.com/questions/54010651/codecov-io-badge-in-github-readme-md

**Comment by ssaru** [comment]
위 PR Approve되면, master에 한번 병합하겠습니다.
