### ISSUE TITLE
[FEATURE] label 정의

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/template#12]
## 🚀 Feature

- 이슈 label을 정의

## Motivation

- 이슈 label을 정의가 없어서, 필요한 기능 카테고리에 대해서 정의가 불가능함

## Pitch

- 이슈 label을 정의가 없어서, 필요한 기능 카테고리에 대해서 정의가 불가능함

## Alternatives

- 이슈 label을 정의하여 이슈 카테고리가 가능하도록 변경

**Comment by aisolab** [comment]
label 정의는 다 같이 진행해야하는 부분일까요?

**Comment by ssaru** [comment]
네네! 그러면 좋을 것 같아요!

**Comment by ssaru** [comment]
저는 기본적으로 아래와 같은 내용을 생각했습니다.
```
- bug
- enhancement or feature
- hotfix
- documents
- refactoring
```

**Comment by ssaru** [comment]
`test` 추가요!

**Comment by ssaru** [comment]
별도의 의견이 없는 것 같으므로 지금까지 논의한 label을 반영하고 이슈를 닫겠습니다.
