### ISSUE TITLE
[FEATURE] 프로젝트 구조 설정

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/template#18]
## 🚀 Feature

- 최소한의 프로젝트 구조(폴더 계층 및 기본 스크립트 파일)을 추가합니다.

## Motivation

- 프로젝트 구조가 잡히면 전체 프로젝트가 템플릿 기반으로 시작하게됩니다.
- 템플릿 기반으로 시작한다는 의미는 사용자 입장에서하는 하나의 프로젝트만 이해하면 다른 프로젝트는 이해하기 쉬운 장점이 있습니다.
- 반대로, 템플릿을 기반으로 시작하면 최소한의 프로젝트 구조를 맞춰야하기 때문에 자유성은 떨어진다는 단점이 있을 것 같습니다.

**Comment by aisolab** [comment]
https://github.com/HephaestusProject/template/issues/33 에서 처리하였으므로, close 하겠습니다.
