### ISSUE TITLE
[FEATURE] 재현성/테스트 코드를 위한 SEED 고정

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/template#19]
## 🚀 Feature

- 재현성과 테스트를 위하여 프로젝트의 난수 SEED를 고정합니다.

## Motivation

- 프로젝트의 SEED가 고정되지 않았을 때, 논문 재현성이 어려워집니다.
- 또한 테스트 코드의 결과도 달라지기 때문에, 에러를 허용하는 방향으로 테스크 코드를 짜야합니다. 이는 개인적으로 비용이 클 것 같습니다.

**Comment by soeque1** [comment]
- 경험 상 Pytorch의 CPU Random number 처리와 GPU의 Random number 처리가 다릅니다. 
   해결 방법 아시는 분은 댓글 부탁드려요.

Furthermore, results need not be reproducible between CPU and GPU executions, even when using identical seeds.

https://pytorch.org/docs/stable/notes/randomness.html

**Comment by ssaru** [comment]
@soeque1 
이호성님의 블로그가 답변이 되지 않을까 생각해봅니다.
아직은 돌려보지 않아서 확인이 필요할 것 같습니다.

https://hoya012.github.io/blog/reproducible_pytorch/

**Comment by ssaru** [comment]
확인해보니 거진 비슷한 내용이군요.

저도 한번 확인해보겠습니다.

**Comment by soeque1** [comment]
- GPU와 CPU 각각에서 재현은 잘됩니다.
- 동일한 테스트 코드에서 CPU와 GPU 사용 시 seed를 고정하더라도 (아래, model('안녕하세요?'))결과가 달라질 수 있다는 얘기였어요.

```
def test:
    model = Model(ctx=cpu or gpu)
    model.seed(123)
    assert model('안녕하세요?') == '네? 안녕하세요'
```

**Comment by ssaru** [comment]
감사합니다.

자세한 테스트 코드는 수치레벨에서 확인하겠지만,
E2E는 최종 아웃풋으로 테스트할 것 같습니다.

염두해서 템플릿을 만들어봐야겠습니다.
도와주실꺼죠?! 🤗

**Comment by ssaru** [comment]
조금 더 테스트해봐야겠지만, pytorch-lightning에  `pytorch_lightning.seed_everything(seed)`가 있네요.

**Comment by ssaru** [comment]
cuDNN seed 고정이 없네여...... ㅠㅠ

```python
def seed_everything(seed: Optional[int] = None) -> int:
    """Function that sets seed for pseudo-random number generators  in:
        pytorch, numpy, python.random and sets PYTHONHASHSEED environment variable.
    """
    max_seed_value = np.iinfo(np.uint32).max
    min_seed_value = np.iinfo(np.uint32).min

    try:
        if seed is None:
            seed = _select_seed_randomly(min_seed_value, max_seed_value)
        else:
            seed = int(seed)
    except (TypeError, ValueError):
        seed = _select_seed_randomly(min_seed_value, max_seed_value)

    if (seed > max_seed_value) or (seed < min_seed_value):
        log.warning(
            f"{seed} is not in bounds, \
            numpy accepts from {min_seed_value} to {max_seed_value}"
        )
        seed = _select_seed_randomly(min_seed_value, max_seed_value)

    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    return seed
```

**Comment by soeque1** [comment]
네, 공유 감사드립니다 ~
test 시  pytorch_lightning.seed_everything(seed) 사용하면 좋을 것 같아요!! 
요 쓰레드는 그만 close 해도 되지 않을까요?

**Comment by ssaru** [comment]
template repository에 seed 고정에 대한 example code를 넣어두려고했는데요.
안넣어도 괜찮을까요?

**Comment by ssaru** [comment]
추가적으로 ` pytorch_lightning.seed_everything(seed)`만으로 충분한지 테스트하기 위해서
테스트를 진행해보려고했었는데요, 제가 확인한 바로는 cuDNN 옵션 없이도 잘 되는 것을 확인했습니다.

cuDNN 옵션 고정은 아래와 같습니다.
```python
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
```

혹시 cuDNN 고정을 안하면 문제가 생기는 사례에 대해서 알고계시는분 계실까요?

**Comment by soeque1** [comment]
@soeque1 반영 된 줄 착각했습니당. 
```
pytorch_lightning.seed_everything(seed)
```
만 일단 넣어두면 되겠습니당
