### ISSUE TITLE
[PAPER] ReCoSa: Detecting the Relevant Contexts with Self-Attention for Multi-turn Dialogue Generation

### ISSUE THREAD

**Issue by soeque1** [HephaestusProject/template#40]
## 📝 Introduction

[NLP] ReCoSa: Detecting the Relevant Contexts with Self-Attention for Multi-turn Dialogue Generation

## Why? 

- Multi-turn inference 시 history(contexts) 정보를 활용할 때 주요한 contexts 추출이 필요합니다.
- Multi-turn Augmentation 시 주요한 contexts 추출이 필요합니다.

는 훼이크고 https://github.com/modulabs/beyondBERT 발표 예정입니다 ㅠ

## Issue card

- [ ] Data Preparing (download and preprocess)
- [ ] Data Loader
- [ ] Model
- [ ] Trainer
- [ ] Logger
- [ ] Configs
- [ ] Hparams
- [ ]  Infernece

## Schedule

1.
2.
3.

## Reference

https://arxiv.org/abs/1907.05339

**Comment by ssaru** [comment]
이거는 논문 구현을 위한 개인 레포를 생성해주시고, 거기에 이슈를 파주시면 될 것 같습니다!
이슈 project만 Automated Kanban으로 잡아주시면 될 것 같아요!

**Comment by ssaru** [comment]
이거는 논문 구현을 위한 개인 레포를 생성해주시고, 거기에 이슈를 파주시면 될 것 같습니다!
이슈 project만 Automated Kanban으로 잡아주시면 될 것 같아요!

**Comment by ssaru** [comment]
👆 이렇게 코멘트를 달았었는데요.
논의가 조금 더 필요할 것 같네요! 👀

**Comment by soeque1** [comment]
@ssaru 개인레포로 가져가고 여기 close 하겠습니당
